In [3]:
%pip install numpy
import numpy as np
A = np.array([ [12, 5, 8, 20], [ 7, 15, 3, 11], [25, 9, 18, 6], [10, 14, 2, 16] ])  

for i in A:
    print(np.mean(i))

index=-1
maxi=0
for i in range(len(A)):
    m=np.mean(A[i])
    cnt=0
    for c in range(len(A[i])):
        if(A[i][c] > m):
            A[i][c]=1
            cnt=cnt+1
        else :
            A[i][c]=0

    if(cnt>maxi):
        maxi=cnt
        index=i
print("The binary matrix is:")
for i in A:
    print(i)
print("Row with maximum number of elements greater than mean is:", index)


Note: you may need to restart the kernel to use updated packages.
11.25
9.0
14.5
10.5
The binary matrix is:
[1 0 0 1]
[0 1 0 1]
[1 0 1 0]
[0 1 0 1]
Row with maximum number of elements greater than mean is: 0


In [4]:
X = np.array([ [10, 100, 5], [12, 110, 6], [11, 105, 7], [13, 500, 6], [14, 108, 8], [15, 115, 9] ]) 

mn = np.mean(X, axis=0)
stdd = np.std(X, axis=0)
mediann = np.median(X, axis=0)
print("mean of col ", mn)
print("mean of std", stdd)


for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        if abs(X[i][j] - mn[j]) > 2 * stdd[j]:
            print("value =", X[i][j])
            X[i][j] = mediann[j]


print(X)

mean of col  [ 12.5        173.           6.83333333]
mean of std [  1.70782513 146.31017281   1.34370962]
value = 500
[[ 10 100   5]
 [ 12 110   6]
 [ 11 105   7]
 [ 13 109   6]
 [ 14 108   8]
 [ 15 115   9]]


In [5]:
#%pip install pandas
import pandas as pd  
df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],  'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],  'Gender': ['F','M','F','M','M','F','F','M'],  'Marks': [85,72,91,65,78,88,95,70], 'Attendance': [92,81,96,72,85,90,98,75] })  

print(df)

print(df.groupby('Department')['Marks'].mean())

print(df.groupby(['Department', 'Gender'])['Marks'].mean())

print(df.loc[df.groupby('Department')['Marks'].idxmax(), ['Department', 'Student', 'Marks']])


depav = df.groupby('Department')['Marks'].transform('mean')

print(df[df['Marks'] > depav])


print(df.groupby('Department')['Attendance'].mean().idxmax())





  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
1       B        CSE      M     72          81
2       C        ECE      F     91          96
3       D        ECE      M     65          72
4       E        CSE      M     78          85
5       F        ECE      F     88          90
6       G        CSE      F     95          98
7       H        ECE      M     70          75
Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64
Department  Gender
CSE         F         90.0
            M         75.0
ECE         F         89.5
            M         67.5
Name: Marks, dtype: float64
  Department Student  Marks
6        CSE       G     95
2        ECE       C     91
  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
2       C        ECE      F     91          96
5       F        ECE      F     88          90
6       G        CSE      F     95          98
CSE


In [7]:
df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],  'Name': ['A','B','C','A','D','B','E'], 'Age': [20,21,22,20,23,21,24],  'Score': [80,75,90,85,88,75,92] })  

duplicated_ids = df[df['ID'].duplicated(keep=False)]['ID'].unique()
print(duplicated_ids)

for id in duplicated_ids:
    records = df[df['ID'] == id]
    print("ID:", id, "records identical:", records.nunique().max() == 1)

clean_df = df.sort_values('Score', ascending=False).drop_duplicates(
    subset='ID',
    keep='first'
)

clean_df = clean_df.sort_values('ID').reset_index(drop=True)
print(clean_df)


print("record removed ",len(df) - len(clean_df))

[101 102]
ID: 101 records identical: False
ID: 102 records identical: True
    ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92
record removed  2


In [8]:
df = pd.DataFrame({ 'Date': [ '2026-01-01', '2026-01-02', '2026-01-04', '2026-01-05', '2026-01-08', '2026-01-09' ],  'Sales': [100,120,150,130,180,200] })  

df['Date'] = pd.to_datetime(df['Date'])
minidate=df['Date'].min()
maxidate=df['Date'].max()

for i in pd.date_range(minidate, maxidate):
    if i not in df['Date'].values:
        print("missing date ", i)




newi =[]
for i in pd.date_range(minidate, maxidate):
    if i not in df['Date'].values:
        newi.append({'Date': i, 'Sales': np.nan})


df=pd.concat([df, pd.DataFrame(newi)], ignore_index=True)
df = df.sort_values('Date').reset_index()
print(df)
print(df['Sales'].rolling(window=3,min_periods=1).mean())


df.loc[df['Sales'].rolling(window=3,min_periods=1).mean().idxmax(), 'Date']





missing date  2026-01-03 00:00:00
missing date  2026-01-06 00:00:00
missing date  2026-01-07 00:00:00
   index       Date  Sales
0      0 2026-01-01  100.0
1      1 2026-01-02  120.0
2      6 2026-01-03    NaN
3      2 2026-01-04  150.0
4      3 2026-01-05  130.0
5      7 2026-01-06    NaN
6      8 2026-01-07    NaN
7      4 2026-01-08  180.0
8      5 2026-01-09  200.0
0    100.0
1    110.0
2    110.0
3    135.0
4    140.0
5    140.0
6    130.0
7    180.0
8    190.0
Name: Sales, dtype: float64


Timestamp('2026-01-09 00:00:00')

In [9]:
P = np.array([ [1, 2], [4, 6], [7, 3], [2, 8], [9, 5] ])  

diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]
D = np.sqrt(np.sum(diff ** 2, axis=2))

print("matrix ", D)
i, j = np.unravel_index(np.argmax(D), D.shape)
print("pair of points ", i, "and", j)


matrix  [[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]
pair of points  0 and 4
